---
title: Functions in Python
author: ''
date: '2020-12-05'
slug: learning-python
categories: []
tags: []
description: ''
---
Being able to use functions is an essential tool in coding. Functions allow you to perform the same set of code over and over again. This helps save time by applying the same task in various situations. Functions often use iteration and conditionals to be able to perform the desired task.

```{python3}
import numpy as np
```

<B>Iteration</B>: for and while loops are used to continually perform a set of code *for* a particular amount of times or *while* a particular statement is true

```{python3}
for i in range(1,11):
    print(2**i)

i=1
while i < 11:
    print(2**i)
    i+=1
```
These two loops have identical outputs but are slightly different in their logic. The for loop initializes a variable (i) then provides a particular condition (in range(1,11)) that will allow the loop to terminate when the condition is exceeded. The while loop takes a previously initialized variable (i) and then provides a condition so that the loop will continue until the condition is no longer true.

<B>Conditionals</B>: if, elif, and else are useful conditionals that allow you to specify perform various code depending on which condition is true.
```{python3}
x=np.random.randint(-10,10,1) #generate a random number from 1 to 10
if x>0:
    print("x is greater than zero!")
elif x==0:
    print("x is zero!")
else:
  print("x is less than zero!")
```
In this example, x is a random integer between -10 and 10. *If*x is greater than one, the output will print the statement under the if conditional. If the if statement is false, the code will move on to the *elif* statement and print the corresponding text if true. Finally, if the elif is also false, the *else* statement will be printed. 

<B>Functions</B>: With the conditionals and iterations above, functions can be created to perform complex code that can be applied to various situations.
```{python3}
longhorn = "BEVO XV is the greatest mascot of all time!"

def count_chars(sentence):
  counts = {}
  for c in sentence:
    if c in counts:
      counts[c]+=1
    else:
       counts[c]=1
  print(counts)
  
count_chars(longhorn)
```
In this example, we have a function that can determine how many times each character appears in a sentence. The function "count_chars" if defined (def) so that anytime is it called the for loop and if-else statements within it will be applied. The empty vector "counts" stores the information which is then printed. My sentence, stored in the string "longhorn", was put through the function by calling "count_chars(longhorn)". Combining the conditionals and iterations within a function allows this set of code to be used for any sentence! 